[package]
name = "mr"
version = "0.1.0"
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
reqwest = "0.9.20"
clap = "2.33.0"
serde_json = "1.0.40"
